# Generated by Django 4.0.2 on 2022-02-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosificaciones',
            fields=[
                ('dosificacion_id', models.AutoField(db_column='dosificacion_id', primary_key=True, serialize=False)),
                ('dosificacion', models.CharField(max_length=250)),
                ('fecha_inicio', utils.custome_db_types.DateFieldCustome(blank=True, null=True)),
                ('fecha_fin', utils.custome_db_types.DateFieldCustome(blank=True, null=True)),
                ('numero_autorizacion', models.CharField(max_length=250)),
                ('llave', models.CharField(max_length=250)),
                ('numero_actual', models.IntegerField()),
                ('user_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('sucursal_id', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.sucursales')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dosificaciones',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('venta_id', models.AutoField(db_column='venta_id', primary_key=True, serialize=False)),
                ('cupon_id', models.IntegerField(default=0)),
                ('cupon', models.CharField(default='', max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('ci_nit', models.CharField(max_length=150)),
                ('telefonos', models.CharField(max_length=150)),
                ('tipo_venta', models.CharField(max_length=50)),
                ('numero_venta', models.IntegerField(default=0)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_id_fecha', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('concepto', models.CharField(max_length=250)),
                ('user_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('almacen_id', models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.almacenes')),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.cajas')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='VentasDetalles',
            fields=[
                ('venta_detalle_id', models.AutoField(db_column='venta_detalle_id', primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventas')),
            ],
            options={
                'db_table': 'ventas_detalles',
            },
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('cupon_id', models.AutoField(db_column='cupon_id', primary_key=True, serialize=False)),
                ('cupon', models.CharField(db_column='cupon', default='', max_length=150)),
                ('numero_usos', models.IntegerField(default=1)),
                ('numero_actual_uso', models.IntegerField(default=0)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'cupones',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura_id', models.AutoField(db_column='factura_id', primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('ci_nit', models.CharField(max_length=150)),
                ('telefonos', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=150)),
                ('factura_a', models.CharField(max_length=250)),
                ('numero_factura', models.IntegerField()),
                ('numero_autorizacion', models.CharField(max_length=250)),
                ('llave', models.CharField(max_length=250)),
                ('codigo_control', models.CharField(max_length=250)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.cajas')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes')),
                ('dosificacion_id', models.ForeignKey(db_column='dosificacion_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.dosificaciones')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventas')),
            ],
            options={
                'db_table': 'facturas',
                'unique_together': {('dosificacion_id', 'numero_factura')},
            },
        ),
    ]
