# Generated by Django 4.0.2 on 2022-03-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(db_column='producto_id', primary_key=True, serialize=False)),
                ('tipo_montura_id', models.CharField(max_length=250)),
                ('material_id', models.CharField(max_length=250)),
                ('producto', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(default='', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('descripcion1', models.CharField(max_length=250)),
                ('descripcion2', models.CharField(max_length=250)),
                ('descripcion3', models.CharField(max_length=250)),
                ('descripcion4', models.CharField(max_length=250)),
                ('descripcion5', models.CharField(max_length=250)),
                ('descripcion6', models.CharField(max_length=250)),
                ('descripcion7', models.CharField(max_length=250)),
                ('descripcion8', models.CharField(max_length=250)),
                ('descripcion9', models.CharField(max_length=250)),
                ('descripcion10', models.CharField(max_length=250)),
                ('novedad', models.BooleanField(default=False)),
                ('mas_vendido', models.BooleanField(default=False)),
                ('oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('linea_id', models.ForeignKey(db_column='linea_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.lineas')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductosTiposMontura',
            fields=[
                ('producto_tipo_montura_id', models.AutoField(db_column='producto_tipo_montura_id', primary_key=True, serialize=False)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('tipo_montura_id', models.ForeignKey(db_column='tipo_montura_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tiposmontura')),
            ],
            options={
                'db_table': 'productos_tipos_montura',
            },
        ),
        migrations.CreateModel(
            name='ProductosRelacionados',
            fields=[
                ('producto_relacionado_id', models.AutoField(db_column='producto_relacionado_id', primary_key=True, serialize=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='primer_prodr', to='productos.productos', verbose_name='prod1r')),
                ('producto_relacion_id', models.ForeignKey(db_column='producto_relacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='segundo_prodr', to='productos.productos', verbose_name='prod2r')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_relacionados',
            },
        ),
        migrations.CreateModel(
            name='ProductosMateriales',
            fields=[
                ('producto_material_id', models.AutoField(db_column='producto_material_id', primary_key=True, serialize=False)),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.materiales')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
            ],
            options={
                'db_table': 'productos_materiales',
            },
        ),
        migrations.CreateModel(
            name='ProductosImagenes',
            fields=[
                ('producto_imagen_id', models.AutoField(db_column='producto_imagen_id', primary_key=True, serialize=False)),
                ('imagen', models.CharField(default='', max_length=250, unique=True)),
                ('imagen_thumb', models.CharField(default='', max_length=250, unique=True)),
                ('posicion', models.IntegerField(default=1)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_imagenes',
            },
        ),
    ]
