# Generated by Django 4.0.2 on 2022-02-10 11:44

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
