# Generated by Django 4.0.2 on 2022-03-28 12:45

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasDias',
            fields=[
                ('reserva_dia_id', models.AutoField(db_column='reserva_dia_id', primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50)),
                ('posicion', models.IntegerField(default=0)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'reservas_dias',
            },
        ),
        migrations.CreateModel(
            name='ReservasHoras',
            fields=[
                ('reserva_hora_id', models.AutoField(db_column='reserva_hora_id', primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=50)),
                ('posicion', models.IntegerField(default=0)),
                ('reserva_dia_id', models.ForeignKey(db_column='reserva_dia_id', on_delete=django.db.models.deletion.PROTECT, to='reservas.reservasdias')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'reservas_horas',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('reserva_id', models.AutoField(db_column='reserva_id', primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField(default=0)),
                ('ci_nit', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=250)),
                ('nombres', models.CharField(max_length=250)),
                ('telefonos', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mensaje', models.TextField()),
                ('fecha_inicio', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_fin', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('reserva_dia_id', models.ForeignKey(db_column='reserva_dia_id', on_delete=django.db.models.deletion.PROTECT, to='reservas.reservasdias')),
                ('reserva_hora_id', models.ForeignKey(db_column='reserva_hora_id', on_delete=django.db.models.deletion.PROTECT, to='reservas.reservashoras')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
